
name: Lets see events

on:
    issues:
        types: opened
    pull_request:
        types: [opened, edited]
        branches:
            - 'develop'
    workflow_dispatch:

jobs:
    Get-Issue:
        runs-on : ubuntu-latest
        steps:
          - name: Get Event Details
            run: echo "${{ toJson(github.event) }}"
                