
name: Lets see events

on:
    issues:
        types: opened
    pull_request:
        types: [opened, edited]  
        branches:
            - 'develop'
    push:
        branches:
            - 'develop'
        # paths:
        #     - 'force-app/**'  # multiple level deep
    workflow_dispatch:

jobs:
    Get-Issue:
        runs-on : ubuntu-latest
        steps:
          - name: Get Event Details
            run: echo "${{ toJson(github.event) }}"
                